#!/usr/bin/env python3
"""Derive the app version from the git tag and write the build-time version files.

Single source of truth for both the local build (packaging/build_app.sh) and CI
(.github/workflows/build-app.yml). Resolution order:

  1. $MILLENIA_VERSION (CI passes the release tag here), else
  2. `git describe --tags --always --dirty`, else
  3. "0.0.0+dev"

A leading "v" is stripped. Side effects:

  * writes  _version.py                        -> imported by millennia_ui.py
  * writes  packaging/windows_version_info.txt -> PyInstaller --version-file (Windows)

and prints the resolved version to stdout so shell steps can capture it:

    VERSION=$(python packaging/make_version.py)
"""

import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
COPYRIGHT = "© 2026 Daniel Côté (DCC-Lab)"


def resolve_version():
    env = os.environ.get("MILLENIA_VERSION", "").strip()
    if env:
        version = env
    else:
        try:
            version = subprocess.check_output(
                ["git", "describe", "--tags", "--always", "--dirty"],
                cwd=ROOT, stderr=subprocess.DEVNULL, text=True,
            ).strip()
        except Exception:
            version = ""
    if not version:
        version = "0.0.0+dev"
    if version[:1] in ("v", "V"):
        version = version[1:]
    return version


def numeric_tuple(version):
    """Leading X.Y.Z of the version as a 4-int tuple (for the Windows resource)."""
    match = re.match(r"(\d+)(?:\.(\d+))?(?:\.(\d+))?", version)
    parts = [int(g) for g in (match.groups() if match else ()) if g]
    parts = (parts + [0, 0, 0, 0])[:4]
    return tuple(parts)


def write_version_module(version):
    (ROOT / "_version.py").write_text(
        '# Generated by packaging/make_version.py — do not edit.\n'
        '__version__ = "{0}"\n'.format(version)
    )


def write_windows_version_file(version):
    a, b, c, d = numeric_tuple(version)
    text = """# Generated by packaging/make_version.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, {d}),
    prodvers=({a}, {b}, {c}, {d}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'DCC-Lab'),
        StringStruct('FileDescription', 'Millennia eV Laser Control'),
        StringStruct('FileVersion', '{ver}'),
        StringStruct('InternalName', 'MilleniaUI'),
        StringStruct('LegalCopyright', '{copy}'),
        StringStruct('OriginalFilename', 'MilleniaUI.exe'),
        StringStruct('ProductName', 'MilleniaUI'),
        StringStruct('ProductVersion', '{ver}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""".format(a=a, b=b, c=c, d=d, ver=version, copy=COPYRIGHT)
    (HERE / "windows_version_info.txt").write_text(text, encoding="utf-8")


def main():
    version = resolve_version()
    write_version_module(version)
    write_windows_version_file(version)
    sys.stdout.write(version + "\n")


if __name__ == "__main__":
    main()
